# permissions for end users to view springbootapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootapplication-viewer-role
rules:
- apiGroups:
  - springboot.qingmu.io
  resources:
  - springbootapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - springboot.qingmu.io
  resources:
  - springbootapplications/status
  verbs:
  - get
