#name: Docker Image CI
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#    - name: Build the Docker image
#      run: make docker-build IMG=freemanliu/spring-boot-operator-controller:${GITHUB_SHA:0:7}
