on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/refs/tags/, '');
      - name: Echo
        run: echo "tag is ${{ steps.tag.outputs.result }}"
      - name: release
        run: |
          echo ${{ steps.create_release.outputs.tag_name }}
          echo ${{ steps.create_release.outputs }}
          echo ${{ steps.create_release.outputs.github.ref }}
          make docker-build docker-push IMG=freemanliu/spring-boot-operator-controller:${{ steps.tag.outputs.result }}
